on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - run: sudo apt-get update && sudo apt-get install -y cpplint
      - uses: pre-commit/action@v3.0.0
